language: r

sudo: required
warnings_are_errors: false
  
r_binary_packages:
  - XML
  - Rcpp
  - knitr

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls();codecov()'
